name: Robot Framework

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on:  ubuntu-latest

  steps:
   uses: actions/checkout@v2
       uses:  nanasess/setup-chromedriver@v1
  run: |
    export DISPLAY=:99
    chromedriver --url-base=/wd/hub &
    sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
  

  name: Setup Python Enviroment
    uses: actions/setup-python@v4
     with:
         python-version: '3.10' 
         name: Install Dependencies
     run:  
        pip install robotframework
        pip install --upgrade robotframework-seleniumlibrary
        pip install robotframework-screencaplibrary

    name: Store Tests Report
    uses: actions/upload-artifact@v3
     if: always()
      with:
        name: reports
        path: path

    

  
